recording:
  on_death: end_recording
  on_change_dimension: end_recording
playback:
  block_actions_playback: true
  block_initialization: true
settings:
  quick_discard: true
  drop_from_blocks: false
  allow_ghosts: true
