package com.ultraop.mocap.recording;

import com.ultraop.mocap.playback.EntityFilter;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.entity.Entity;
import org.bukkit.entity.Player;
import org.bukkit.plugin.java.JavaPlugin;
import org.bukkit.scheduler.BukkitTask;
import java.io.IOException;
import java.nio.file.Path;
import java.util.*;

/** Owns active recordings, completed recordings and saved recording files. */
public final class RecordingManager {
    private final JavaPlugin plugin; private final RecordingRepository repository;
    private final Map<UUID,RecordingSession> active=new LinkedHashMap<>(), completed=new LinkedHashMap<>(); private final Map<String,RecordingSession> saved=new LinkedHashMap<>(); private BukkitTask ticker;
    private final Map<UUID,Location> waitingForAction=new HashMap<>(); private final Map<UUID,RecordingSession> waitingForRespawn=new HashMap<>();
    private final Set<UUID> pendingStop=new HashSet<>(), safeDiscard=new HashSet<>();
    private RecordingSession.OnDeath onDeath=RecordingSession.OnDeath.END_RECORDING; private OnChangeDimension onChangeDimension=OnChangeDimension.END_RECORDING;
    private double entityTrackingDistance=128.0; private EntityFilter trackEntities=EntityFilter.DEFAULT_TRACK_ENTITIES; private boolean preventTrackingPlayedEntities=true,assignDimension=true,startInstantly=false,chatRecording=false,quickDiscard=true;
    public RecordingManager(JavaPlugin plugin){this.plugin=plugin;this.repository=new RecordingRepository(Path.of(plugin.getDataFolder().getPath(),"recordings"));}
    public void start(){if(ticker!=null)return;loadSettings();try{repository.initialize();saved.clear();saved.putAll(repository.loadAll());}catch(IOException e){plugin.getLogger().severe("Unable to load saved recordings: "+e.getMessage());}ticker=Bukkit.getScheduler().runTaskTimer(plugin,this::tick,1L,1L);}
    public void reloadSettings(){loadSettings();}
    private void loadSettings(){String death=plugin.getConfig().getString("recording.on_death",plugin.getConfig().getString("settings.on_death",onDeath.name()));String dimension=plugin.getConfig().getString("recording.on_change_dimension",plugin.getConfig().getString("settings.on_change_dimension",onChangeDimension.name()));try{onDeath=RecordingSession.OnDeath.valueOf(death.toUpperCase(Locale.ROOT));}catch(IllegalArgumentException ignored){onDeath=RecordingSession.OnDeath.END_RECORDING;}try{onChangeDimension=OnChangeDimension.valueOf(dimension.toUpperCase(Locale.ROOT));}catch(IllegalArgumentException ignored){onChangeDimension=OnChangeDimension.END_RECORDING;}entityTrackingDistance=plugin.getConfig().getDouble("settings.entity_tracking_distance",128.0);if(!Double.isFinite(entityTrackingDistance))entityTrackingDistance=128.0;trackEntities=new EntityFilter(plugin.getConfig().getString("settings.track_entities",EntityFilter.DEFAULT_TRACK_ENTITIES.expression()));preventTrackingPlayedEntities=plugin.getConfig().getBoolean("settings.prevent_tracking_played_entities",true);assignDimension=plugin.getConfig().getBoolean("settings.assign_dimension",true);startInstantly=plugin.getConfig().getBoolean("settings.start_instantly",false);chatRecording=plugin.getConfig().getBoolean("settings.chat_recording",false);quickDiscard=plugin.getConfig().getBoolean("settings.quick_discard",true);}
    public RecordingSession.OnDeath getOnDeath(){return onDeath;} public void setOnDeath(RecordingSession.OnDeath value){onDeath=value==null?RecordingSession.OnDeath.END_RECORDING:value;plugin.getConfig().set("recording.on_death",onDeath.name().toLowerCase(Locale.ROOT));plugin.saveConfig();}
    public OnChangeDimension getOnChangeDimension(){return onChangeDimension;} public void setOnChangeDimension(OnChangeDimension value){onChangeDimension=value==null?OnChangeDimension.END_RECORDING:value;plugin.getConfig().set("recording.on_change_dimension",value.name().toLowerCase(Locale.ROOT));plugin.saveConfig();}
    public double getEntityTrackingDistance(){return entityTrackingDistance;} public EntityFilter getTrackEntities(){return trackEntities;} public boolean isPreventTrackingPlayedEntities(){return preventTrackingPlayedEntities;} public boolean isAssignDimension(){return assignDimension;} public boolean isStartInstantly(){return startInstantly;} public boolean isChatRecording(){return chatRecording;} public boolean isQuickDiscard(){return quickDiscard;}
    public RecordingSession startRecording(Player p){for(RecordingSession existing:active.values())if(existing.getSourcePlayerId().equals(p.getUniqueId())){if(existing.isWaitingForAction()){waitingForAction.remove(existing.getId());existing.start();}return existing;}for(RecordingSession existing:completed.values())if(existing.getSourcePlayerId().equals(p.getUniqueId())&&existing.isWaitingForDecision()){return existing;}RecordingSession s=new RecordingSession(p,entityTrackingDistance,trackEntities,preventTrackingPlayedEntities,assignDimension);s.setOnDeath(onDeath);s.setOnChangeDimension(onChangeDimension);active.put(s.getId(),s);if(startInstantly)s.start();else waitingForAction.put(s.getId(),p.getLocation().clone());return s;} public RecordingSession startRecording(Player p,String name){RecordingSession s=startRecording(p);if(name!=null&&!name.isBlank())s.setInstantSaveName(name);return s;}
    public void markSwing(Player p,boolean offHand){for(RecordingSession s:active.values())if(s.getSourcePlayerId().equals(p.getUniqueId())){if(offHand)s.markSwingOffHand(p);else s.markSwingMainHand(p);}}
    public void markHurt(Entity entity){for(RecordingSession s:active.values())s.markHurt(entity);}
    public void recordChat(Player sender,String messageJson){if(!chatRecording||sender==null)return;for(RecordingSession s:active.values())if(s.getSourcePlayerId().equals(sender.getUniqueId()))s.recordChat(messageJson);}
    public RecordingSession stopRecording(UUID id){RecordingSession activeSession=active.get(id);if(activeSession!=null){waitingForAction.remove(id);waitingForRespawn.remove(activeSession.getSourcePlayerId());activeSession.stopForDecision(false);if(activeSession.getState()==RecordingSession.State.CANCELED){active.remove(id);return activeSession;}complete(activeSession,false);return activeSession;}RecordingSession pending=completed.get(id);if(pending!=null&&pendingStop.contains(id)){if(pending.requiresSafeDiscard()){pending.markSafeDiscardSatisfied();safeDiscard.remove(id);return pending;}pending.discard();pendingStop.remove(id);safeDiscard.remove(id);completed.remove(id);return pending;}return null;}
    private void complete(RecordingSession s,boolean automaticallyStopped){completed.put(s.getId(),s);if(s.getInstantSaveName()!=null){try{save(s.getInstantSaveName(),s);}catch(IOException e){plugin.getLogger().severe("Unable to instantly save recording: "+e.getMessage());}return;}if(automaticallyStopped||quickDiscard)pendingStop.add(s.getId());if(automaticallyStopped)safeDiscard.add(s.getId());}
    public RecordingSession stopRecordingForPlayer(Player p){for(RecordingSession s:new ArrayList<>(active.values()))if(s.getSourcePlayerId().equals(p.getUniqueId()))return stopRecording(s.getId());for(RecordingSession s:new ArrayList<>(completed.values()))if(s.getSourcePlayerId().equals(p.getUniqueId())&&pendingStop.contains(s.getId()))return stopRecording(s.getId());return null;}
    public RecordingSession discard(UUID id){RecordingSession s=active.remove(id);waitingForAction.remove(id);pendingStop.remove(id);safeDiscard.remove(id);if(s!=null){waitingForRespawn.remove(s.getSourcePlayerId());s.discard();return s;}s=completed.remove(id);if(s!=null){pendingStop.remove(id);safeDiscard.remove(id);s.discard();}return s;}
    public RecordingSession get(UUID id){RecordingSession s=active.get(id);return s!=null?s:completed.get(id);}
    public Collection<RecordingSession> getActive(){return ListView.copyOf(active.values());} public Collection<RecordingSession> getCompleted(){return ListView.copyOf(completed.values());} public Collection<String> getSavedNames(){return ListView.copyOf(saved.keySet());} public RecordingSession getSaved(String n){return saved.get(n);}
    public boolean save(String n,RecordingSession s)throws IOException{repository.save(n,s);saved.put(n,s);pendingStop.remove(s.getId());safeDiscard.remove(s.getId());s.markSaved();return true;} public boolean save(String n,UUID id)throws IOException{RecordingSession s=get(id);return s!=null&&save(n,s);}
    public boolean rename(String old,String n)throws IOException{if(!saved.containsKey(old)||saved.containsKey(n)||repository.exists(n))return false;RecordingSession s=saved.remove(old);repository.save(n,s);repository.delete(old);saved.put(n,s);return true;} public boolean copy(String old,String n)throws IOException{if(saved.containsKey(n)||repository.exists(n))return false;RecordingSession s=saved.get(old);if(s==null)return false;repository.save(n,s);saved.put(n,s);return true;} public boolean removeSaved(String n)throws IOException{boolean r=repository.delete(n);saved.remove(n);return r;}
    public void shutdown(){if(ticker!=null){ticker.cancel();ticker=null;}waitingForAction.clear();waitingForRespawn.clear();pendingStop.clear();safeDiscard.clear();active.clear();completed.clear();saved.clear();}
    public void handleRespawn(Player oldPlayer,Player newPlayer){RecordingSession s=waitingForRespawn.remove(oldPlayer.getUniqueId());if(s==null)return;if(!s.onRespawn(newPlayer))return;active.remove(s.getId());waitingForAction.remove(s.getId());complete(s,true);RecordingSession next=startRecording(newPlayer);plugin.getLogger().fine("Recording split on respawn: "+s.getId()+" -> "+next.getId());}
    private void tick(){for(RecordingSession s:new ArrayList<>(active.values())){Player p=Bukkit.getPlayer(s.getSourcePlayerId());if(p==null||!p.isOnline()){active.remove(s.getId());waitingForAction.remove(s.getId());waitingForRespawn.remove(s.getSourcePlayerId());s.stopForDecision(true);complete(s,true);continue;}Location waitLocation=waitingForAction.get(s.getId());if(waitLocation!=null){if(hasMoved(p,waitLocation)){waitingForAction.remove(s.getId());s.start();}else continue;}if(s.isDead())waitingForRespawn.putIfAbsent(p.getUniqueId(),s);boolean split=s.capture(p);if(split){active.remove(s.getId());waitingForAction.remove(s.getId());waitingForRespawn.remove(s.getSourcePlayerId());complete(s,true);RecordingSession next=startRecording(p);plugin.getLogger().fine("Recording split on dimension change: "+s.getId()+" -> "+next.getId());continue;}if(s.getState()==RecordingSession.State.WAITING_FOR_DECISION){active.remove(s.getId());waitingForAction.remove(s.getId());waitingForRespawn.remove(s.getSourcePlayerId());complete(s,true);}}}
    private boolean hasMoved(Player p,Location start){Location now=p.getLocation();if(!now.getWorld().equals(start.getWorld()))return true;return now.distanceSquared(start)>1.0E-8||Math.abs(now.getYaw()-start.getYaw())>1.0E-4f||Math.abs(now.getPitch()-start.getPitch())>1.0E-4f;}
    private static final class ListView{static<T>Collection<T> copyOf(Collection<T> c){return Collections.unmodifiableList(new ArrayList<>(c));}}
}
