package com.ultraop.mocap.recording;

import com.mojang.authlib.GameProfile;
import com.mojang.authlib.properties.Property;
import com.ultraop.mocap.playback.EntityFilter;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.ListTag;
import net.minecraft.nbt.Tag;
import net.minecraft.resources.Identifier;
import net.minecraft.util.ProblemReporter;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.level.storage.TagValueOutput;
import org.bukkit.craftbukkit.entity.CraftEntity;
import org.bukkit.entity.Entity;
import org.bukkit.entity.LivingEntity;
import org.bukkit.entity.Player;
import org.bukkit.entity.Mob;
import java.time.Instant;
import java.util.*;

/** In-memory recording produced by one recording session. */
public final class RecordingSession {
    public enum State { WAITING_FOR_ACTION, RECORDING, WAITING_FOR_DECISION, CANCELED, DISCARDED, SAVED }
    public enum OnDeath { END_RECORDING, CONTINUE_SYNCED, CONTINUE_SKIP_TICKS, SPLIT_RECORDING }
    public record AssignedProfile(String name, UUID id, String skinValue, String skinSignature) { }
    private final double entityTrackingDistance; private final EntityFilter trackEntities; private final boolean preventTrackingPlayedEntities;
    private final UUID id,sourcePlayerId; private final String sourcePlayerName; private final Instant startedAt; private final String assignedDimensionKey;
    private final List<PlayerStateFrame> frames; private final Map<UUID,List<EntityStateFrame>> entityFrames; private final List<BlockActionFrame> blockActions; private final List<ChatMessageFrame> chatMessages;
    private final Map<UUID,Integer> trackedLastSeenTick; private final Set<UUID> swingMainHand=new HashSet<>(),swingOffHand=new HashSet<>(),hurt=new HashSet<>();
    private String instantSaveName; private long nextTick; private Instant stoppedAt; private OnDeath onDeath=OnDeath.END_RECORDING; private boolean died; private long diedTick=-1;
    private OnChangeDimension onChangeDimension=OnChangeDimension.END_RECORDING; private String lastWorldKey; private State state=State.WAITING_FOR_ACTION; private boolean requiresSafeDiscard;
    private String assignProfileMode="no"; private AssignedProfile assignedProfile;
    public RecordingSession(Player p){this(p,128.0,EntityFilter.DEFAULT_TRACK_ENTITIES,true,true);}
    public RecordingSession(Player p,double trackingDistance,EntityFilter filter){this(p,trackingDistance,filter,true,true);}
    public RecordingSession(Player p,double trackingDistance,EntityFilter filter,boolean preventTrackingPlayedEntities){this(p,trackingDistance,filter,preventTrackingPlayedEntities,true);}
    public RecordingSession(Player p,double trackingDistance,EntityFilter filter,boolean preventTrackingPlayedEntities,boolean assignDimension){this(UUID.randomUUID(),p.getUniqueId(),p.getName(),Instant.now(),null,new ArrayList<>(),new LinkedHashMap<>(),new ArrayList<>(),new ArrayList<>(),trackingDistance,filter==null?EntityFilter.disabled():filter,preventTrackingPlayedEntities,assignDimension?worldKey(p):null);lastWorldKey=worldKey(p);}
    private RecordingSession(UUID id,UUID pid,String pn,Instant start,Instant stop,List<PlayerStateFrame> frames,Map<UUID,List<EntityStateFrame>> entities,List<BlockActionFrame> blocks,List<ChatMessageFrame> chats,double trackingDistance,EntityFilter filter,boolean preventTrackingPlayedEntities,String assignedDimensionKey){this.id=id;sourcePlayerId=pid;sourcePlayerName=pn;startedAt=start;stoppedAt=stop;this.frames=new ArrayList<>(frames);entityFrames=new LinkedHashMap<>();entities.forEach((u,v)->entityFrames.put(u,new ArrayList<>(v)));blockActions=new ArrayList<>(blocks);chatMessages=new ArrayList<>(chats);trackedLastSeenTick=new LinkedHashMap<>();entityFrames.forEach((u,v)->{if(!v.isEmpty())trackedLastSeenTick.put(u,Math.toIntExact(v.get(v.size()-1).tick()));});nextTick=frames.stream().mapToLong(PlayerStateFrame::tick).max().orElse(-1L)+1L;lastWorldKey=frames.isEmpty()?null:frames.get(frames.size()-1).worldKey();entityTrackingDistance=trackingDistance;trackEntities=filter;this.preventTrackingPlayedEntities=preventTrackingPlayedEntities;this.assignedDimensionKey=assignedDimensionKey;this.state=stop==null?State.WAITING_FOR_ACTION:State.WAITING_FOR_DECISION;}
    static RecordingSession loaded(UUID id,UUID pid,String pn,Instant start,Instant stop,List<PlayerStateFrame> f){return loaded(id,pid,pn,start,stop,f,Map.of(),List.of(),List.of(),null);}
    static RecordingSession loaded(UUID id,UUID pid,String pn,Instant start,Instant stop,List<PlayerStateFrame> f,Map<UUID,List<EntityStateFrame>> e){return loaded(id,pid,pn,start,stop,f,e,List.of(),List.of(),null);}
    static RecordingSession loaded(UUID id,UUID pid,String pn,Instant start,Instant stop,List<PlayerStateFrame> f,Map<UUID,List<EntityStateFrame>> e,List<BlockActionFrame> b){return loaded(id,pid,pn,start,stop,f,e,b,List.of(),null);}
    static RecordingSession loaded(UUID id,UUID pid,String pn,Instant start,Instant stop,List<PlayerStateFrame> f,Map<UUID,List<EntityStateFrame>> e,List<BlockActionFrame> b,String assignedDimensionKey){return loaded(id,pid,pn,start,stop,f,e,b,List.of(),assignedDimensionKey);}
    static RecordingSession loaded(UUID id,UUID pid,String pn,Instant start,Instant stop,List<PlayerStateFrame> f,Map<UUID,List<EntityStateFrame>> e, List<BlockActionFrame> b,List<ChatMessageFrame> chats,String assignedDimensionKey){return new RecordingSession(id,pid,pn,start,stop,f,e,b,chats,128.0,EntityFilter.DEFAULT_TRACK_ENTITIES,true,assignedDimensionKey);}
    public UUID getId(){return id;} public UUID getSourcePlayerId(){return sourcePlayerId;} public String getSourcePlayerName(){return sourcePlayerName;} public Instant getStartedAt(){return startedAt;} public Instant getStoppedAt(){return stoppedAt;} public String getAssignedDimensionKey(){return assignedDimensionKey;} public long getDurationTicks(){return frames.size();} public List<PlayerStateFrame> getFrames(){return Collections.unmodifiableList(frames);}
    public Map<UUID,List<EntityStateFrame>> getEntityFrames(){Map<UUID,List<EntityStateFrame>> c=new LinkedHashMap<>();entityFrames.forEach((u,v)->c.put(u,Collections.unmodifiableList(v)));return Collections.unmodifiableMap(c);} public List<BlockActionFrame> getBlockActions(){return Collections.unmodifiableList(blockActions);} public List<ChatMessageFrame> getChatMessages(){return Collections.unmodifiableList(chatMessages);}
    public String getInstantSaveName(){return instantSaveName;} public void setInstantSaveName(String n){instantSaveName=n;} public OnDeath getOnDeath(){return onDeath;} public void setOnDeath(OnDeath v){onDeath=v==null?OnDeath.END_RECORDING:v;} public OnChangeDimension getOnChangeDimension(){return onChangeDimension;} public void setOnChangeDimension(OnChangeDimension v){onChangeDimension=v==null?OnChangeDimension.END_RECORDING:v;}
    public State getState(){return state;} public boolean isWaitingForAction(){return state==State.WAITING_FOR_ACTION;} public boolean isWaitingForDecision(){return state==State.WAITING_FOR_DECISION;} public boolean requiresSafeDiscard(){return requiresSafeDiscard;} public AssignedProfile getAssignedProfile(){return assignedProfile;}
    void setAssignProfileMode(String mode){assignProfileMode=mode==null?"no":mode.toLowerCase(Locale.ROOT);} void setAssignedProfile(AssignedProfile p){assignedProfile=p;}
    void start(){if(state==State.WAITING_FOR_ACTION){state=State.RECORDING;if(!"no".equals(assignProfileMode))captureAssignedProfile();}}
    private void captureAssignedProfile(){try{GameProfile p=((org.bukkit.craftbukkit.entity.CraftPlayer)BukkitAccess.player(sourcePlayerId)).getProfile();String name=p.name();UUID id="full".equals(assignProfileMode)?p.id():null;Property skin=p.properties().get("textures").stream().findFirst().orElse(null);String value="full".equals(assignProfileMode)&&skin!=null?skin.value():null;String signature="full".equals(assignProfileMode)&&skin!=null?skin.signature():null;assignedProfile=new AssignedProfile(name,id,value,signature);}catch(Exception ignored){assignedProfile=new AssignedProfile(sourcePlayerName,"full".equals(assignProfileMode)?sourcePlayerId:null,null,null);}}
    void stopForDecision(boolean safeDiscard){if(state==State.RECORDING){state=State.WAITING_FOR_DECISION;stop();requiresSafeDiscard=safeDiscard;}else if(state==State.WAITING_FOR_ACTION){state=State.CANCELED;stop();}}
    void discard(){if(state==State.WAITING_FOR_ACTION){state=State.CANCELED;stop();}else if(state==State.WAITING_FOR_DECISION){state=State.DISCARDED;requiresSafeDiscard=false;}}
    void markSaved(){state=State.SAVED;requiresSafeDiscard=false;} void markSafeDiscardSatisfied(){requiresSafeDiscard=false;}
    void markSwingMainHand(Player p){if(activeFor(p))swingMainHand.add(p.getUniqueId());} void markSwingOffHand(Player p){if(activeFor(p))swingOffHand.add(p.getUniqueId());} void markHurt(Entity e){if(activeFor(e))hurt.add(e.getUniqueId());}
    void recordChat(String messageJson){if(stoppedAt==null&&chatRecordingEnabled())chatMessages.add(new ChatMessageFrame(currentTick(),messageJson));}
    private boolean chatRecordingEnabled(){return JavaPluginAccess.plugin().getConfig().getBoolean("settings.chat_recording",false);}
    private boolean activeFor(Entity e){return sourcePlayerId.equals(e.getUniqueId())||trackedLastSeenTick.containsKey(e.getUniqueId());}
    boolean capture(Player p){if(stoppedAt!=null)return false;if(state==State.WAITING_FOR_ACTION)start();if(state!=State.RECORDING)return false;String currentWorld=worldKey(p);if(lastWorldKey!=null&&!lastWorldKey.equals(currentWorld)){if(onChangeDimension==OnChangeDimension.END_RECORDING){stopForDecision(true);return false;}if(onChangeDimension==OnChangeDimension.SPLIT_RECORDING){stopForDecision(true);return true;}}if(died){captureDeadTick(p);return false;}UUID u=p.getUniqueId();boolean main=swingMainHand.remove(u),off=swingOffHand.remove(u),wasHurt=hurt.remove(u);frames.add(PlayerStateFrame.capture(p,nextTick,main,off,wasHurt));trackEntities(p);if(p.isDead()){died=true;diedTick=nextTick;}nextTick++;lastWorldKey=currentWorld;return false;}
    private void captureDeadTick(Player p){long diff=nextTick-diedTick;if(onDeath==OnDeath.CONTINUE_SYNCED||onDeath==OnDeath.CONTINUE_SKIP_TICKS||diff<20){UUID u=p.getUniqueId();boolean main=swingMainHand.remove(u),off=swingOffHand.remove(u),wasHurt=hurt.remove(u);frames.add(PlayerStateFrame.capture(p,nextTick,main,off,wasHurt));trackEntities(p);nextTick++;}if(diff>=20&&onDeath==OnDeath.END_RECORDING)stopForDecision(true);}
    boolean onRespawn(Player newPlayer){if(onDeath!=OnDeath.SPLIT_RECORDING){died=false;diedTick=-1;lastWorldKey=worldKey(newPlayer);return false;}stopForDecision(true);return true;}
    public boolean isDead(){return died;} public void recordBlockAction(BlockActionFrame a){if(a!=null&&state==State.RECORDING)blockActions.add(a);}
    public long currentTick(){return Math.max(0,nextTick-1);}
    private void trackEntities(Player p){if(!trackEntities.enabled())return;double max=entityTrackingDistance<0?Double.POSITIVE_INFINITY:entityTrackingDistance*entityTrackingDistance;Set<UUID> seen=new HashSet<>();for(Entity e:p.getWorld().getEntities()){if(e instanceof Player||!e.isValid()||e.getUniqueId().equals(sourcePlayerId))continue;if((entityTrackingDistance>=0&&p.getLocation().distanceSquared(e.getLocation())>max)||(preventTrackingPlayedEntities&&isPlaybackEntity(e))||!trackEntities.matches(e))continue;UUID id=e.getUniqueId();seen.add(id);boolean wasHurt=hurt.remove(id);entityFrames.computeIfAbsent(id,x->new ArrayList<>()).add(EntityStateFrame.capture(e,nextTick,wasHurt,captureEntityNbt(e)));trackedLastSeenTick.put(id,Math.toIntExact(nextTick));}trackedLastSeenTick.keySet().removeIf(u->!seen.contains(u));}
    private String captureEntityNbt(Entity e){String mode=JavaPluginAccess.plugin().getConfig().getString("settings.nbt_recording_mode","filtered");if("disabled".equalsIgnoreCase(mode))return null;try{var handle=((CraftEntity)e).getHandle();var out=TagValueOutput.createWithContext(ProblemReporter.DISCARDING,handle.registryAccess());handle.saveWithoutId(out);CompoundTag nbt=out.buildResult();nbt.putString("id",e.getType().getKey().toString());nbt.remove("UUID");nbt.remove("Pos");nbt.remove("Motion");if("filtered".equalsIgnoreCase(mode))filterEntityNbt(nbt,e);return nbt.toString();}catch(Exception ignored){return null;}}
    private void filterEntityNbt(CompoundTag nbt,Entity entity){nbt.remove("Brain");nbt.remove("EggLayTime");nbt.remove("CanPickUpLoot");nbt.remove("NoAI");nbt.remove("ForcedAge");nbt.remove("fall_distance");if(nbt.getShortOr("HurtTime",(short)-1)==0)nbt.remove("HurtTime");if(nbt.getShortOr("DeathTime",(short)-1)==0)nbt.remove("DeathTime");if(nbt.getIntOr("HurtByTimestamp",-1)==0)nbt.remove("HurtByTimestamp");if(entity instanceof LivingEntity living&&nbt.getShortOr("Air",(short)-1)==living.getMaximumAir())nbt.remove("Air");if(nbt.getFloatOr("AbsorptionAmount",-1.0f)==0.0f)nbt.remove("AbsorptionAmount");if(entity instanceof LivingEntity living&&nbt.getFloatOr("Health",-1.0f)==living.getMaxHealth())nbt.remove("Health");if(nbt.getIntOr("Age",-1)>=0)nbt.remove("Age");else nbt.putInt("Age",-9);ListTag list=nbt.getList("attributes").orElse(null);if(list!=null){ListTag filtered=new ListTag();for(Tag tag:list){CompoundTag attribute=tag.asCompound().orElse(null);String id=attribute==null?null:attribute.getString("id").orElse(null);Identifier attr=id==null?null:Identifier.tryParse(id);if(attr==null){filtered.add(tag);continue;}if(Attributes.FOLLOW_RANGE.is(attr)||Attributes.ATTACK_DAMAGE.is(attr)||Attributes.FALL_DAMAGE_MULTIPLIER.is(attr)||Attributes.SAFE_FALL_DISTANCE.is(attr))continue;filtered.add(tag);}if(filtered.isEmpty())nbt.remove("attributes");else nbt.put("attributes",filtered);}}
    private static boolean isPlaybackEntity(Entity e){return e.getScoreboardTags().stream().anyMatch(t->t.equals("mocap_entity")||t.equals("mocap:entity"));} private static String worldKey(Player p){return p.getWorld().getKey().toString();}
    void stop(){trackedLastSeenTick.clear();swingMainHand.clear();swingOffHand.clear();hurt.clear();if(stoppedAt==null)stoppedAt=Instant.now();}
    static final class BukkitAccess { static Player player(UUID id){return org.bukkit.Bukkit.getPlayer(id);} }
    static final class JavaPluginAccess { static org.bukkit.plugin.java.JavaPlugin plugin(){return org.bukkit.plugin.java.JavaPlugin.getProvidingPlugin(RecordingSession.class);} }
}
