package com.ultraop.mocap.recording;

import org.bukkit.entity.Pose;
import org.bukkit.inventory.EquipmentSlot;
import org.bukkit.inventory.ItemStack;
import org.bukkit.util.io.BukkitObjectInputStream;
import org.bukkit.util.io.BukkitObjectOutputStream;
import java.io.*; import java.nio.file.*; import java.time.Instant; import java.util.*;

/** Persistent storage for saved MoCap recordings. */
public final class RecordingRepository {
    private static final int FORMAT_VERSION=6; private final Path directory;
    public RecordingRepository(Path directory){this.directory=directory;} public void initialize()throws IOException{Files.createDirectories(directory);}
    public void save(String name,RecordingSession s)throws IOException{validateName(name);initialize();try(DataOutputStream out=new DataOutputStream(new BufferedOutputStream(Files.newOutputStream(pathFor(name))))){out.writeInt(FORMAT_VERSION);out.writeUTF(s.getId().toString());out.writeUTF(s.getSourcePlayerId().toString());out.writeUTF(s.getSourcePlayerName());out.writeUTF(s.getStartedAt().toString());out.writeBoolean(s.getStoppedAt()!=null);if(s.getStoppedAt()!=null)out.writeUTF(s.getStoppedAt().toString());out.writeInt(s.getFrames().size());out.writeInt(s.getEntityFrames().size());out.writeInt(s.getBlockActions().size());try(BukkitObjectOutputStream o=new BukkitObjectOutputStream(out)){for(PlayerStateFrame f:s.getFrames())writeFrame(o,f);for(var e:s.getEntityFrames().entrySet()){out.writeUTF(e.getKey().toString());out.writeInt(e.getValue().size());for(EntityStateFrame f:e.getValue())writeEntityFrame(o,f);}for(BlockActionFrame a:s.getBlockActions())writeBlockAction(o,a);}}}
    public RecordingSession load(String name)throws IOException{validateName(name);Path source=pathFor(name);if(!Files.isRegularFile(source))return null;try(DataInputStream in=new DataInputStream(new BufferedInputStream(Files.newInputStream(source)))){if(in.readInt()!=FORMAT_VERSION)throw new IOException("Unsupported recording format version");UUID id=UUID.fromString(in.readUTF()),pid=UUID.fromString(in.readUTF());String pn=in.readUTF();Instant start=Instant.parse(in.readUTF()),stop=in.readBoolean()?Instant.parse(in.readUTF()):null;int fc=in.readInt(),ec=in.readInt(),bc=in.readInt();if(fc<0||fc>10000000||ec<0||ec>1000000||bc<0||bc>10000000)throw new IOException("Invalid recording counts");List<PlayerStateFrame> frames=new ArrayList<>(fc);Map<UUID,List<EntityStateFrame>> entities=new LinkedHashMap<>();List<BlockActionFrame> blocks=new ArrayList<>(bc);try(BukkitObjectInputStream o=new BukkitObjectInputStream(in)){for(int i=0;i<fc;i++)frames.add(readFrame(o));for(int i=0;i<ec;i++){UUID eid=UUID.fromString(in.readUTF());int n=in.readInt();if(n<0||n>10000000)throw new IOException("Invalid entity frame count");List<EntityStateFrame> v=new ArrayList<>(n);for(int j=0;j<n;j++)v.add(readEntityFrame(o));entities.put(eid,v);}for(int i=0;i<bc;i++)blocks.add(readBlockAction(o));}return RecordingSession.loaded(id,pid,pn,start,stop,frames,entities,blocks);}catch(EOFException e){throw new IOException("Truncated recording: "+name,e);}}
    public Map<String,RecordingSession> loadAll()throws IOException{initialize();Map<String,RecordingSession> r=new LinkedHashMap<>();try(var st=Files.list(directory)){for(Path p:st.filter(x->x.getFileName().toString().endsWith(".mocap")).sorted().toList()){String f=p.getFileName().toString();r.put(f.substring(0,f.length()-6),load(f.substring(0,f.length()-6)));}}return r;}
    public boolean delete(String n)throws IOException{validateName(n);return Files.deleteIfExists(pathFor(n));} public boolean exists(String n){return Files.isRegularFile(pathFor(n));} public List<String> list()throws IOException{initialize();try(var s=Files.list(directory)){return s.filter(p->p.getFileName().toString().endsWith(".mocap")).map(p->p.getFileName().toString().replaceFirst("\\.mocap$","")).sorted(String.CASE_INSENSITIVE_ORDER).toList();}}
    private Path pathFor(String n){return directory.resolve(n+".mocap").normalize();} private static void validateName(String n)throws IOException{if(n==null||n.isBlank()||n.length()>128||!n.matches("[A-Za-z0-9._-]+"))throw new IOException("Invalid recording name");}
    private static void writeFrame(ObjectOutputStream o,PlayerStateFrame f)throws IOException{ o.writeLong(f.tick());o.writeUTF(f.worldKey());o.writeDouble(f.x());o.writeDouble(f.y());o.writeDouble(f.z());o.writeFloat(f.yaw());o.writeFloat(f.pitch());o.writeDouble(f.velocityX());o.writeDouble(f.velocityY());o.writeDouble(f.velocityZ());o.writeBoolean(f.onGround());o.writeBoolean(f.sprinting());o.writeBoolean(f.sneaking());o.writeBoolean(f.swimming());o.writeBoolean(f.gliding());o.writeBoolean(f.flying());o.writeUTF(f.pose().name());o.writeFloat(f.fallDistance());o.writeInt(f.fireTicks());o.writeBoolean(f.invisible());o.writeBoolean(f.glowing());o.writeBoolean(f.invulnerable());o.writeDouble(f.health());o.writeObject(f.mainHand());o.writeObject(f.offHand());o.writeInt(f.armor().length);for(ItemStack i:f.armor())o.writeObject(i);writeUuid(o,f.vehicleId());o.writeBoolean(f.swingMainHand());o.writeBoolean(f.swingOffHand());o.writeBoolean(f.activeItemUse());o.writeBoolean(f.activeItemHand()!=null);if(f.activeItemHand()!=null)o.writeUTF(f.activeItemHand().name());o.writeObject(f.activeItem());o.writeInt(f.activeItemUsedTime());o.writeInt(f.activeItemRemainingTime());}
    private static PlayerStateFrame readFrame(ObjectInputStream in)throws IOException{try{long t=in.readLong();String w=in.readUTF();double x=in.readDouble(),y=in.readDouble(),z=in.readDouble();float yaw=in.readFloat(),pitch=in.readFloat();double vx=in.readDouble(),vy=in.readDouble(),vz=in.readDouble();boolean g=in.readBoolean(),sp=in.readBoolean(),sn=in.readBoolean(),sw=in.readBoolean(),gl=in.readBoolean(),fl=in.readBoolean();Pose p=Pose.valueOf(in.readUTF());float fall=in.readFloat();int fire=in.readInt();boolean inv=in.readBoolean(),go=in.readBoolean(),iu=in.readBoolean();double hp=in.readDouble();ItemStack main=(ItemStack)in.readObject(),off=(ItemStack)in.readObject();int ac=in.readInt();if(ac<0||ac>8)throw new IOException("Invalid armor count");ItemStack[] ar=new ItemStack[ac];for(int i=0;i<ac;i++)ar[i]=(ItemStack)in.readObject();UUID vid=readUuid(in);boolean sm=in.readBoolean(),so=in.readBoolean();boolean active=in.readBoolean();EquipmentSlot hand=in.readBoolean()?EquipmentSlot.valueOf(in.readUTF()):null;ItemStack activeItem=(ItemStack)in.readObject();int used=in.readInt(),remaining=in.readInt();return new PlayerStateFrame(t,w,x,y,z,yaw,pitch,vx,vy,vz,g,sp,sn,sw,gl,fl,p,fall,fire,inv,go,iu,hp,main,off,ar,vid,sm,so,active,hand,activeItem,used,remaining);}catch(ClassNotFoundException|IllegalArgumentException e){throw new IOException("Invalid player frame",e);}}
    private static void writeEntityFrame(ObjectOutputStream o,EntityStateFrame f)throws IOException{o.writeLong(f.tick());o.writeUTF(f.entityId().toString());o.writeUTF(f.entityType());o.writeUTF(f.worldKey());o.writeDouble(f.x());o.writeDouble(f.y());o.writeDouble(f.z());o.writeFloat(f.yaw());o.writeFloat(f.pitch());o.writeDouble(f.velocityX());o.writeDouble(f.velocityY());o.writeDouble(f.velocityZ());o.writeUTF(f.pose().name());o.writeFloat(f.fallDistance());o.writeInt(f.fireTicks());o.writeBoolean(f.invisible());o.writeBoolean(f.glowing());o.writeBoolean(f.invulnerable());o.writeDouble(f.health());o.writeObject(f.mainHand());o.writeObject(f.offHand());o.writeInt(f.armor().length);for(ItemStack i:f.armor())o.writeObject(i);writeUuid(o,f.vehicleId());}
    private static EntityStateFrame readEntityFrame(ObjectInputStream in)throws IOException{try{long t=in.readLong();UUID id=UUID.fromString(in.readUTF());String type=in.readUTF(),w=in.readUTF();double x=in.readDouble(),y=in.readDouble(),z=in.readDouble();float yaw=in.readFloat(),pitch=in.readFloat();double vx=in.readDouble(),vy=in.readDouble(),vz=in.readDouble();Pose pose=Pose.valueOf(in.readUTF());float fall=in.readFloat();int fire=in.readInt();boolean inv=in.readBoolean(),go=in.readBoolean(),iu=in.readBoolean();double hp=in.readDouble();ItemStack main=(ItemStack)in.readObject(),off=(ItemStack)in.readObject();int ac=in.readInt();if(ac<0||ac>8)throw new IOException("Invalid entity armor count");ItemStack[] ar=new ItemStack[ac];for(int i=0;i<ac;i++)ar[i]=(ItemStack)in.readObject();return new EntityStateFrame(t,id,type,w,x,y,z,yaw,pitch,vx,vy,vz,pose,fall,fire,inv,go,iu,hp,main,off,ar,readUuid(in));}catch(ClassNotFoundException|IllegalArgumentException e){throw new IOException("Invalid entity frame",e);}}
    private static void writeBlockAction(ObjectOutputStream o,BlockActionFrame a)throws IOException{o.writeLong(a.tick());o.writeUTF(a.worldKey());o.writeInt(a.x());o.writeInt(a.y());o.writeInt(a.z());o.writeUTF(a.action().name());o.writeUTF(a.beforeState());o.writeUTF(a.afterState());}
    private static BlockActionFrame readBlockAction(ObjectInputStream in)throws IOException{try{return new BlockActionFrame(in.readLong(),in.readUTF(),in.readInt(),in.readInt(),in.readInt(),BlockActionFrame.Action.valueOf(in.readUTF()),in.readUTF(),in.readUTF());}catch(IllegalArgumentException e){throw new IOException("Invalid block action",e);}}
    private static void writeUuid(ObjectOutputStream o,UUID u)throws IOException{if(u==null){o.writeBoolean(false);return;}o.writeBoolean(true);o.writeLong(u.getMostSignificantBits());o.writeLong(u.getLeastSignificantBits());} private static UUID readUuid(ObjectInputStream i)throws IOException{if(!i.readBoolean())return null;return new UUID(i.readLong(),i.readLong());}
}
