package com.ultraop.mocap.command;

import com.ultraop.mocap.playback.PlaybackManager;
import com.ultraop.mocap.playback.PlaybackModifiers;
import com.ultraop.mocap.playback.PlaybackSession;
import com.ultraop.mocap.playback.PlaybackSynchronization;
import com.ultraop.mocap.recording.RecordingManager;
import com.ultraop.mocap.recording.RecordingSession;
import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.command.*;
import org.bukkit.entity.Entity;
import org.bukkit.entity.Player;
import org.bukkit.plugin.java.JavaPlugin;
import org.jetbrains.annotations.NotNull;
import java.io.IOException;
import java.util.*;

public final class MoCapCommand implements CommandExecutor, TabCompleter {
    private final JavaPlugin plugin; private final RecordingManager recordingManager; private final PlaybackManager playbackManager;
    public MoCapCommand(JavaPlugin plugin, RecordingManager recordingManager, PlaybackManager playbackManager){this.plugin=plugin;this.recordingManager=recordingManager;this.playbackManager=playbackManager;}
    @Override public boolean onCommand(@NotNull CommandSender sender,@NotNull Command command,@NotNull String label,@NotNull String[] args){if(!sender.hasPermission("mocap.use")){sender.sendMessage(ChatColor.RED+"You do not have permission to use /mocap.");return true;}if(args.length==0||args[0].equalsIgnoreCase("help")){sendHelp(sender);return true;}switch(args[0].toLowerCase(Locale.ROOT)){case "recording"->handleRecording(sender,args);case "recordings"->handleRecordings(sender,args);case "playback"->handlePlayback(sender,args);case "info"->{sender.sendMessage(ChatColor.GRAY+"MoCap Paper 0.1.0-SNAPSHOT");sender.sendMessage(ChatColor.GRAY+"Paper 1.21.11 feature-parity implementation.");}case "scenes","settings"->sender.sendMessage(ChatColor.RED+"That MoCap command is not implemented yet.");case "misc"->handleMisc(sender,args);default->sendHelp(sender);}return true;}
    private void handleMisc(CommandSender s,String[] a){if(a.length<2||!a[1].equalsIgnoreCase("sync")){s.sendMessage(ChatColor.YELLOW+"Usage: /mocap misc sync <enable|disable>");return;}if(!(s instanceof Player p)){s.sendMessage(ChatColor.RED+"A player is required for synchronization.");return;}if(a.length<3){s.sendMessage(ChatColor.YELLOW+"Usage: /mocap misc sync <enable|disable>");return;}boolean enable=a[2].equalsIgnoreCase("enable"),disable=a[2].equalsIgnoreCase("disable");if(!enable&&!disable){s.sendMessage(ChatColor.YELLOW+"Usage: /mocap misc sync <enable|disable>");return;}boolean old=PlaybackSynchronization.set(p.getUniqueId(),enable);if(enable)s.sendMessage(old?ChatColor.GREEN+"Synchronization has already been enabled":ChatColor.GREEN+"Synchronization enabled");else s.sendMessage(old?ChatColor.GREEN+"Synchronization disabled":ChatColor.GREEN+"Synchronization has already been disabled");}
    private void handlePlayback(CommandSender s,String[] a){if(a.length<2){s.sendMessage(ChatColor.YELLOW+"Usage: /mocap playback <start|stop|stop_all|modifiers|list>");return;}switch(a[1].toLowerCase(Locale.ROOT)){case "start"->startPlayback(s,a);case "stop"->stopPlayback(s,a);case "stop_all"->stopAllPlayback(s,a);case "modifiers"->handleModifiers(s,a);case "list"->listPlayback(s);default->s.sendMessage(ChatColor.YELLOW+"Usage: /mocap playback <start|stop|stop_all|modifiers|list>");}}
    private void startPlayback(CommandSender s,String[] a){if(a.length<3){s.sendMessage(ChatColor.YELLOW+"Usage: /mocap playback start <name> [player|selector]");return;}RecordingSession r=recordingManager.getSaved(a[2]);if(r==null){s.sendMessage(ChatColor.RED+"Recording not found: "+a[2]);return;}List<Player> viewers=resolvePlayers(s,a.length>=4?a[3]:null);if(viewers.isEmpty())return;int started=0;for(Player p:viewers){PlaybackSession x=playbackManager.play(r,p);if(x!=null){s.sendMessage(ChatColor.GREEN+"Playback started: "+x.getId()+" ("+a[2]+")");started++;}}if(started==0)s.sendMessage(ChatColor.RED+"Playback could not be started.");}
    private List<Player> resolvePlayers(CommandSender s,String selector){if(selector==null){if(s instanceof Player p)return List.of(p);s.sendMessage(ChatColor.RED+"Specify a player when executing this from console.");return List.of();}try{List<Player> out=new ArrayList<>();for(Entity e:Bukkit.selectEntities(s,selector))if(e instanceof Player p)out.add(p);if(out.isEmpty())s.sendMessage(ChatColor.RED+"No players matched the playback target.");return out;}catch(IllegalArgumentException e){s.sendMessage(ChatColor.RED+"Invalid or unresolved player selector: "+selector);return List.of();}}
    private void stopPlayback(CommandSender s,String[] a){if(a.length<3){s.sendMessage(ChatColor.YELLOW+"Usage: /mocap playback stop <id>");return;}UUID id=parseUuid(s,a[2]);if(id==null)return;PlaybackSession x=playbackManager.stop(id);s.sendMessage(x==null?ChatColor.RED+"Playback not found: "+a[2]:ChatColor.GREEN+"Playback stopped: "+a[2]);}
    private void stopAllPlayback(CommandSender s,String[] a){if(a.length>=3&&a[2].equalsIgnoreCase("including_others")){s.sendMessage(ChatColor.GREEN+"Stopped "+playbackManager.stopAll(null)+" playback(s).");return;}if(!(s instanceof Player p)){s.sendMessage(ChatColor.RED+"Specify 'including_others' when executing this from console.");return;}s.sendMessage(ChatColor.GREEN+"Stopped "+playbackManager.stopAll(p)+" playback(s).");}
    private void handleModifiers(CommandSender s,String[] a){if(!(s instanceof Player p)){s.sendMessage(ChatColor.RED+"A player is required for playback modifiers.");return;}if(a.length<3||a[2].equalsIgnoreCase("list")){listModifiers(s,p);return;}if(a[2].equalsIgnoreCase("reset")){playbackManager.resetModifiers(p);s.sendMessage(ChatColor.GREEN+"Playback modifiers reset.");return;}if(!a[2].equalsIgnoreCase("set")||a.length<5){s.sendMessage(ChatColor.YELLOW+"Usage: /mocap playback modifiers <set|list|reset> ...");return;}try{PlaybackModifiers cur=playbackManager.getModifiers(p);PlaybackModifiers next=switch(a[3].toLowerCase(Locale.ROOT)){case "time"->setTime(cur,a);case "transformations"->setTransform(cur,a);default->throw new IllegalArgumentException("Unknown modifier group: "+a[3]);};playbackManager.setModifiers(p,next);s.sendMessage(ChatColor.GREEN+"Playback modifier updated.");}catch(IllegalArgumentException e){s.sendMessage(ChatColor.RED+e.getMessage());}}
    private PlaybackModifiers setTime(PlaybackModifiers m,String[] a){if(a.length<6)throw new IllegalArgumentException("Usage: ... time <start_delay|wait_on_start|wait_on_end|wait_for_parent_end|loop> <value>");return switch(a[4].toLowerCase(Locale.ROOT)){case "start_delay"->m.withStartDelay(nonNeg(a[5]));case "wait_on_start"->m.withWaitOnStart(nonNeg(a[5]));case "wait_on_end"->m.withWaitOnEnd(nonNeg(a[5]));case "wait_for_parent_end"->m.withWaitForParentEnd(bool(a[5]));case "loop"->m.withLoop(bool(a[5]));default->throw new IllegalArgumentException("Unknown time modifier: "+a[4]);};}
    private PlaybackModifiers setTransform(PlaybackModifiers m,String[] a){if(a.length<6)throw new IllegalArgumentException("Missing transformation value.");return switch(a[4].toLowerCase(Locale.ROOT)){case "rotation"->m.withRotation(Double.parseDouble(a[5]));case "mirror"->m.withMirror(PlaybackModifiers.Mirror.valueOf(a[5].toUpperCase(Locale.ROOT)));case "scale"->{if(a.length<7)throw new IllegalArgumentException("Usage: ... transformations scale <of_player|of_scene> <scale>");double v=nonNeg(a[6]);yield switch(a[5].toLowerCase(Locale.ROOT)){case "of_player"->m.withPlayerScale(v);case "of_scene"->m.withSceneScale(v);default->throw new IllegalArgumentException("Scale target must be of_player or of_scene.");};}case "offset"->{if(a.length<8)throw new IllegalArgumentException("Usage: ... transformations offset <x> <y> <z>");yield m.withOffset(Double.parseDouble(a[5]),Double.parseDouble(a[6]),Double.parseDouble(a[7]));}case "config"->setTransformConfig(m,a);default->throw new IllegalArgumentException("Unknown transformation modifier: "+a[4]);};}
    private PlaybackModifiers setTransformConfig(PlaybackModifiers m,String[] a){if(a.length<7)throw new IllegalArgumentException("Usage: ... transformations config <round_block_pos|recording_center|scene_center|center_offset> ...");PlaybackModifiers.TransformationConfig c=m.transformationConfig();return switch(a[5].toLowerCase(Locale.ROOT)){case "round_block_pos"->m.withTransformationConfig(c.withRoundBlockPos(bool(a[6])));case "recording_center"->m.withTransformationConfig(c.withRecordingCenter(PlaybackModifiers.RecordingCenter.valueOf(a[6].toUpperCase(Locale.ROOT))));case "scene_center"->{PlaybackModifiers.SceneCenterType t=PlaybackModifiers.SceneCenterType.valueOf(a[6].toUpperCase(Locale.ROOT));String specific=t==PlaybackModifiers.SceneCenterType.COMMON_SPECIFIC?arg(a,7,"specific scene element"):null;yield m.withTransformationConfig(c.withSceneCenter(t,specific));}case "center_offset"->{if(a.length<9)throw new IllegalArgumentException("Usage: ... transformations config center_offset <x> <y> <z>");yield m.withTransformationConfig(c.withCenterOffset(Double.parseDouble(a[6]),Double.parseDouble(a[7]),Double.parseDouble(a[8])));}default->throw new IllegalArgumentException("Unknown transformation config: "+a[5]);};}
    private void listModifiers(CommandSender s,Player p){PlaybackModifiers m=playbackManager.getModifiers(p);PlaybackModifiers.TransformationConfig c=m.transformationConfig();s.sendMessage(ChatColor.GOLD+"Playback modifiers:");s.sendMessage(ChatColor.GRAY+"  time: start_delay="+m.startDelaySeconds()+", wait_on_start="+m.waitOnStartSeconds()+", wait_on_end="+m.waitOnEndSeconds()+", wait_for_parent_end="+m.waitForParentEnd()+", loop="+m.loop());s.sendMessage(ChatColor.GRAY+"  transformations: rotation="+m.rotationDegrees()+", mirror="+m.mirror()+", player_scale="+m.playerScale()+", scene_scale="+m.sceneScale());s.sendMessage(ChatColor.GRAY+"  offset: "+m.offsetX()+", "+m.offsetY()+", "+m.offsetZ());s.sendMessage(ChatColor.GRAY+"  config: round_block_pos="+c.roundBlockPos()+", recording_center="+c.recordingCenter()+", scene_center="+c.sceneCenterType()+(c.sceneCenterSpecific()==null?"":" ["+c.sceneCenterSpecific()+"]")+", center_offset="+c.centerOffsetX()+", "+c.centerOffsetY()+", "+c.centerOffsetZ());}
    private void listPlayback(CommandSender s){List<PlaybackSession> xs=new ArrayList<>(playbackManager.getActive());s.sendMessage(ChatColor.GOLD+"Active playbacks: "+xs.size());for(PlaybackSession x:xs)s.sendMessage(ChatColor.GRAY+"  "+x.getId()+" | "+x.getRecording().getSourcePlayerName()+" | tick "+x.getTick());}
    private void handleRecording(CommandSender s,String[] a){if(a.length<2){s.sendMessage(ChatColor.YELLOW+"Usage: /mocap recording <start|stop|discard|save|list>");return;}switch(a[1].toLowerCase(Locale.ROOT)){case "start"->startRecording(s,a);case "stop"->stopRecording(s,a);case "discard"->discardRecording(s,a);case "save"->saveRecording(s,a);case "list"->listRecording(s,a);default->s.sendMessage(ChatColor.YELLOW+"Usage: /mocap recording <start|stop|discard|save|list>");}}
    private void startRecording(CommandSender s,String[] a){List<Player> ps=new ArrayList<>();if(a.length==2){if(s instanceof Player p)ps.add(p);else{s.sendMessage(ChatColor.RED+"Specify a player when executing this from console.");return;}}else{try{for(Entity e:Bukkit.selectEntities(s,a[2]))if(e instanceof Player p)ps.add(p);}catch(IllegalArgumentException e){s.sendMessage(ChatColor.RED+"Invalid or unresolved player selector: "+a[2]);return;}if(ps.isEmpty()){s.sendMessage(ChatColor.RED+"No players matched the recording target.");return;}}String instant=a.length>=4?a[3]:null;for(Player p:ps){String save=ps.size()>1&&instant!=null?instant+"_"+p.getName():instant;RecordingSession x=recordingManager.startRecording(p,save);switch(x.getState()){case WAITING_FOR_ACTION->s.sendMessage(ChatColor.GREEN+"Recording waiting for action: "+x.getId()+" ("+p.getName()+")");case RECORDING->s.sendMessage(ChatColor.GREEN+"Recording started: "+x.getId()+" ("+p.getName()+")");case WAITING_FOR_DECISION->s.sendMessage(ChatColor.YELLOW+"Recording is waiting for decision: "+x.getId()+" ("+p.getName()+")");default->s.sendMessage(ChatColor.RED+"Recording is in state "+x.getState()+": "+x.getId());}}}
    private void stopRecording(CommandSender s,String[] a){RecordingSession x;if(a.length>=3){UUID id=parseRecordingId(s,a[2]);if(id==null)return;x=recordingManager.stopRecording(id);}else if(s instanceof Player p)x=recordingManager.stopRecordingForPlayer(p);else{s.sendMessage(ChatColor.RED+"Specify a recording id when executing this from console.");return;}if(x==null){s.sendMessage(ChatColor.RED+"No active recording was found.");return;}switch(x.getState()){case WAITING_FOR_DECISION->s.sendMessage(x.requiresSafeDiscard()?ChatColor.YELLOW+"Recording stopped; safe discard is required before it can be discarded: "+x.getId():ChatColor.GREEN+"Recording stopped: "+x.getId()+" ("+x.getDurationTicks()+" ticks)");case DISCARDED->s.sendMessage(ChatColor.GREEN+"Recording discarded: "+x.getId());case CANCELED->s.sendMessage(ChatColor.GREEN+"Recording canceled: "+x.getId());case SAVED->s.sendMessage(ChatColor.GREEN+"Recording saved as: "+x.getInstantSaveName());default->s.sendMessage(ChatColor.GREEN+"Recording stopped: "+x.getId()+" ("+x.getDurationTicks()+" ticks)");}if(x.getInstantSaveName()!=null&&x.getState()==RecordingSession.State.SAVED)s.sendMessage(ChatColor.GREEN+"Saved as: "+x.getInstantSaveName());}
    private void discardRecording(CommandSender s,String[] a){RecordingSession x;if(a.length>=3){UUID id=parseRecordingId(s,a[2]);if(id==null)return;x=recordingManager.discard(id);}else if(s instanceof Player p){x=recordingManager.stopRecordingForPlayer(p);x=x==null?null:recordingManager.discard(x.getId());}else{s.sendMessage(ChatColor.RED+"Specify a recording id when executing this from console.");return;}s.sendMessage(x==null?ChatColor.RED+"No recording was found.":x.getState()==RecordingSession.State.CANCELED?ChatColor.GREEN+"Recording canceled: "+x.getId():ChatColor.GREEN+"Recording discarded: "+x.getId());}
    private void saveRecording(CommandSender s,String[] a){if(a.length<3){s.sendMessage(ChatColor.YELLOW+"Usage: /mocap recording save <name> [id]");return;}String name=a[2];RecordingSession x=null;if(a.length>=4){UUID id=parseRecordingId(s,a[3]);if(id==null)return;x=recordingManager.get(id);}else if(s instanceof Player p)x=recordingManager.getCompleted().stream().filter(v->v.getSourcePlayerId().equals(p.getUniqueId())&&v.getState()==RecordingSession.State.WAITING_FOR_DECISION).max(Comparator.comparing(RecordingSession::getStoppedAt,Comparator.nullsFirst(Comparator.naturalOrder()))).orElse(null);else x=recordingManager.getCompleted().stream().filter(v->v.getState()==RecordingSession.State.WAITING_FOR_DECISION).max(Comparator.comparing(RecordingSession::getStoppedAt,Comparator.nullsFirst(Comparator.naturalOrder()))).orElse(null);if(x==null){s.sendMessage(ChatColor.RED+"No completed recording is available to save.");return;}try{recordingManager.save(name,x);s.sendMessage(ChatColor.GREEN+"Recording saved as: "+name);}catch(IOException e){s.sendMessage(ChatColor.RED+"Unable to save recording: "+e.getMessage());}}
    private void listRecording(CommandSender s,String[] a){if(a.length>=3){UUID id=parseRecordingId(s,a[2]);if(id==null)return;RecordingSession x=recordingManager.get(id);if(x==null){s.sendMessage(ChatColor.RED+"Recording not found: "+a[2]);return;}sendRecordingInfo(s,x);return;}Collection<RecordingSession> active=recordingManager.getActive(),done=recordingManager.getCompleted();s.sendMessage(ChatColor.GOLD+"Recording contexts: "+(active.size()+done.size()));for(RecordingSession x:active)sendRecordingInfo(s,x);for(RecordingSession x:done)sendRecordingInfo(s,x);}
    private void handleRecordings(CommandSender s,String[] a){if(a.length<2||a[1].equalsIgnoreCase("list")){s.sendMessage(ChatColor.GOLD+"Saved recordings: "+recordingManager.getSavedNames().size());for(String n:recordingManager.getSavedNames()){RecordingSession x=recordingManager.getSaved(n);s.sendMessage(ChatColor.GRAY+"  "+n+" | "+x.getDurationTicks()+" ticks | "+x.getSourcePlayerName()+" | "+x.getState());}return;}try{switch(a[1].toLowerCase(Locale.ROOT)){case "copy"->{req(s,a,4,"/mocap recordings copy <src_name> <dest_name>");if(a.length>=4)s.sendMessage(recordingManager.copy(a[2],a[3])?ChatColor.GREEN+"Recording copied.":ChatColor.RED+"Unable to copy recording.");}case "rename"->{req(s,a,4,"/mocap recordings rename <old_name> <new_name>");if(a.length>=4)s.sendMessage(recordingManager.rename(a[2],a[3])?ChatColor.GREEN+"Recording renamed.":ChatColor.RED+"Unable to rename recording.");}case "remove"->{req(s,a,3,"/mocap recordings remove <name>");if(a.length>=3)s.sendMessage(recordingManager.removeSaved(a[2])?ChatColor.GREEN+"Recording removed.":ChatColor.RED+"Recording not found.");}case "info"->{req(s,a,3,"/mocap recordings info <name>");if(a.length>=3){RecordingSession x=recordingManager.getSaved(a[2]);if(x==null)s.sendMessage(ChatColor.RED+"Recording not found.");else sendRecordingInfo(s,x);}}default->s.sendMessage(ChatColor.YELLOW+"Usage: /mocap recordings <copy|rename|remove|info|list> ...");}}catch(Exception e){s.sendMessage(ChatColor.RED+e.getMessage());}}
    private void sendRecordingInfo(CommandSender s,RecordingSession x){s.sendMessage(ChatColor.GRAY+"  id="+x.getId()+" player="+x.getSourcePlayerName()+" state="+x.getState()+" ticks="+x.getDurationTicks()+" frames="+x.getFrames().size()+(x.requiresSafeDiscard()?" safe_discard=true":""));}
    private void sendHelp(CommandSender s){s.sendMessage(ChatColor.GOLD+"/mocap recording|recordings|playback|info|help");}
    private void req(CommandSender s,String[] a,int n,String usage){if(a.length<n)s.sendMessage(ChatColor.YELLOW+"Usage: "+usage);}
    private String arg(String[] a,int i,String label){if(a.length<=i)throw new IllegalArgumentException("Missing "+label+".");return a[i];}
    private boolean bool(String v){if(!v.equalsIgnoreCase("true")&&!v.equalsIgnoreCase("false"))throw new IllegalArgumentException("Value must be true or false.");return Boolean.parseBoolean(v);}
    private double nonNeg(String v){double d=Double.parseDouble(v);if(!Double.isFinite(d)||d<0)throw new IllegalArgumentException("Value must be a finite non-negative number.");return d;}
    private UUID parseUuid(CommandSender s,String v){try{return UUID.fromString(v);}catch(IllegalArgumentException e){s.sendMessage(ChatColor.RED+"Invalid UUID: "+v);return null;}}
    private UUID parseRecordingId(CommandSender s,String value){try{return UUID.fromString(value);}catch(IllegalArgumentException ignored){}String id=value.startsWith("-")?value.substring(1):value;String[] p=id.split("\\.");if(p.length<1||p.length>3){s.sendMessage(ChatColor.RED+"Invalid recording id: "+value);return null;}String player=p.length==3?p[1]:p[0];String number=p.length==3?p[2]:p.length==2?p[1]:"1";if(player.equals("_")||number.equals("_")){s.sendMessage(ChatColor.RED+"A single recording id is required: "+value);return null;}try{long wanted=Long.parseLong(number),n=0;List<RecordingSession> all=new ArrayList<>();all.addAll(recordingManager.getActive());all.addAll(recordingManager.getCompleted());all.sort(Comparator.comparing(RecordingSession::getStartedAt));for(RecordingSession x:all)if(x.getSourcePlayerName().equals(player)&&++n==wanted)return x.getId();}catch(NumberFormatException ignored){}s.sendMessage(ChatColor.RED+"Recording not found: "+value);return null;}
    public void shutdown(){}
    @Override public List<String> onTabComplete(@NotNull CommandSender sender,@NotNull Command command,@NotNull String alias,@NotNull String[] args){return List.of();}
}
