package com.ultraop.mocap.playback;

import com.mojang.authlib.GameProfile;
import com.mojang.authlib.properties.Property;
import com.ultraop.mocap.recording.BlockActionFrame;
import com.ultraop.mocap.recording.ChatMessageFrame;
import com.ultraop.mocap.recording.EntityStateFrame;
import com.ultraop.mocap.recording.PlayerStateFrame;
import com.ultraop.mocap.recording.RecordingSession;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.serializer.gson.GsonComponentSerializer;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.World;
import org.bukkit.block.data.BlockData;
import org.bukkit.craftbukkit.entity.CraftPlayer;
import org.bukkit.craftbukkit.CraftServer;
import org.bukkit.entity.Entity;
import org.bukkit.entity.EntityType;
import org.bukkit.entity.Player;
import org.bukkit.plugin.java.JavaPlugin;
import org.bukkit.util.Vector;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.UUID;

/** Tick-driven playback timeline backed by server-side playback actors. */
public final class PlaybackSession {
    private final UUID id = UUID.randomUUID(); private final RecordingSession recording; private final UUID viewerPlayerId; private final List<PlayerStateFrame> frames; private final Map<UUID,List<EntityStateFrame>> entityFrames; private final List<BlockActionFrame> blockActions; private final List<ChatMessageFrame> chatMessages; private final Map<UUID,EntityPlaybackActor> entityActors=new LinkedHashMap<>(); private final FakePlayer fakePlayer; private final EntityPlaybackActor entityActor; private final PlaybackModifiers modifiers; private final PositionTransformer transformer; private final World targetWorld; private final boolean root,blockActionsPlayback,blockInitialization,blockAllowScaled,invulnerablePlayback,preventTrackingPlayedEntities,chatPlayback,allowGhosts; private final String assignProfileMode,playerNameHandling; private final boolean startAsRecorded; private final EntityFilter playEntities; private long tick,waitTicks,waitOnEnd; private boolean paused,finished,stopped;
    public PlaybackSession(RecordingSession r,Player v){this(r,v,PlaybackModifiers.DEFAULT,null,true,true,true,EntityFilter.ALL,true,true,v.getWorld(),"no","ignore_casing",true,false,true);} public PlaybackSession(RecordingSession r,Player v,PlaybackModifiers m){this(r,v,m,null,true,true,true,EntityFilter.ALL,true,true,v.getWorld(),"no","ignore_casing",true,false,true);} public PlaybackSession(RecordingSession r,Player v,PlaybackModifiers m,PositionTransformer p){this(r,v,m,p,false,true,true,EntityFilter.ALL,true,true,v.getWorld(),"no","ignore_casing",true,false,true);} public PlaybackSession(RecordingSession r,Player v,PlaybackModifiers m,PositionTransformer p,boolean root){this(r,v,m,p,root,true,true,EntityFilter.ALL,true,true,v.getWorld(),"no","ignore_casing",true,false,true);} public PlaybackSession(RecordingSession r,Player v,PlaybackModifiers m,PositionTransformer p,boolean root,boolean bap,boolean bi,EntityFilter pe,boolean ip,boolean pte){this(r,v,m,p,root,bap,bi,pe,ip,pte,v.getWorld(),"no","ignore_casing",true,false,true);} public PlaybackSession(RecordingSession r,Player v,PlaybackModifiers m,PositionTransformer p,boolean root,boolean bap,boolean bi,EntityFilter pe,boolean ip,boolean pte,World tw){this(r,v,m,p,root,bap,bi,pe,ip,pte,tw,"no","ignore_casing",true,false,true);} public PlaybackSession(RecordingSession r,Player v,PlaybackModifiers m,PositionTransformer p,boolean root,boolean bap,boolean bi,EntityFilter pe,boolean ip,boolean pte,World tw,String ap,String pnh,boolean cp){this(r,v,m,p,root,bap,bi,pe,ip,pte,tw,ap,pnh,cp,false,true);}
    public PlaybackSession(RecordingSession r,Player v,PlaybackModifiers m,PositionTransformer p,boolean root,boolean bap,boolean bi,EntityFilter pe,boolean ip,boolean pte,World tw,String ap,String pnh,boolean cp,boolean sar){this(r,v,m,p,root,bap,bi,pe,ip,pte,tw,ap,pnh,cp,sar,true);}
    public PlaybackSession(RecordingSession r,Player v,PlaybackModifiers m,PositionTransformer p,boolean root,boolean bap,boolean bi,EntityFilter pe,boolean ip,boolean pte,World tw,String ap,String pnh,boolean cp,boolean sar,boolean allowGhosts){recording=r;viewerPlayerId=v.getUniqueId();frames=r.getFrames();entityFrames=r.getEntityFrames();blockActions=r.getBlockActions();chatMessages=r.getChatMessages();modifiers=m==null?PlaybackModifiers.DEFAULT:m;this.root=root;blockActionsPlayback=bap;blockInitialization=bi;blockAllowScaled=JavaPlugin.getProvidingPlugin(PlaybackSession.class).getConfig().getBoolean("settings.block_allow_scaled",false);playEntities=pe==null?EntityFilter.ALL:pe;invulnerablePlayback=ip;preventTrackingPlayedEntities=pte;assignProfileMode=ap==null?"no":ap;playerNameHandling=pnh==null?"ignore_casing":pnh;chatPlayback=cp;startAsRecorded=sar;this.allowGhosts=allowGhosts;targetWorld=tw==null?v.getWorld():tw;transformer=new PositionTransformer(modifiers,p,calculateRecordingCenter());if(frames.isEmpty()){fakePlayer=null;entityActor=null;stopped=true;return;}PlayerStateFrame f=frames.get(0);Location spawn=transform(new Location(targetWorld,f.x(),f.y(),f.z(),f.yaw(),f.pitch()));if(modifiers.playerAsEntity().enabled()&&modifiers.playerAsEntity().entityType()!=EntityType.PLAYER){Entity e=targetWorld.spawnEntity(spawn,modifiers.playerAsEntity().entityType());entityActor=new EntityPlaybackActor(e,modifiers.playerScale(),invulnerablePlayback);fakePlayer=allowGhosts?FakePlayer.spawn(spawn,resolveProfile(v),1.0,invulnerablePlayback):null;}else{fakePlayer=FakePlayer.spawn(spawn,resolveProfile(v),modifiers.playerScale(),invulnerablePlayback);entityActor=null;}waitTicks=secondsToTicks(modifiers.startDelaySeconds()+modifiers.waitOnStartSeconds());if(waitTicks==0){initializeBlocks();applyFrame(f);applyHitRange(f);applyEntityFrames();applyRidingRelationships(f);applyBlockActions(0);applyChatMessages(0);}}
    public UUID getId(){return id;} public RecordingSession getRecording(){return recording;} public long getTick(){return tick;} public boolean isPaused(){return paused;} public boolean isStopped(){return stopped;} public boolean isFinished(){return finished;} public boolean isActive(){return !stopped&&(!finished||modifiers.loop()||!modifiers.waitForParentEnd());} public UUID getViewerPlayerId(){return viewerPlayerId;} public FakePlayer getFakePlayer(){return fakePlayer;} public EntityPlaybackActor getEntityActor(){return entityActor;} public PlaybackModifiers getModifiers(){return modifiers;} public PlayerStateFrame currentFrame(){return frames.isEmpty()||tick>=frames.size()?null:frames.get((int)tick);} public void pause(){if(!stopped)paused=true;} public void resume(){if(!stopped)paused=false;}
    public void stop(){if(stopped)return;stopped=true;finished=true;ejectPlayer();if(fakePlayer!=null)fakePlayer.remove();if(entityActor!=null)entityActor.remove();removeRecordedEntities();}
    public void advance(){if(paused||stopped)return;if(waitTicks>0){waitTicks--;return;}if(finished){if(modifiers.loop())restartLoop();else if(shouldSelfStop())stop();return;}if(waitOnEnd>0){waitOnEnd--;if(waitOnEnd==0){finished=true;if(modifiers.loop())restartLoop();else if(shouldSelfStop())stop();}return;}if(tick>=frames.size()){finishOrWaitOnEnd();return;}PlayerStateFrame f=frames.get((int)tick);applyFrame(f);applyHitRange(f);applyEntityFrames();applyRidingRelationships(f);applyBlockActions(tick);applyChatMessages(tick);tick++;}
    private void finishOrWaitOnEnd(){long n=secondsToTicks(modifiers.waitOnEndSeconds());if(n==0){finished=true;if(modifiers.loop())restartLoop();else if(shouldSelfStop())stop();}else waitOnEnd=n;} private void restartLoop(){ejectPlayer();removeRecordedEntities();initializeBlocks();tick=0;waitTicks=0;waitOnEnd=0;finished=false;if(!frames.isEmpty()){applyFrame(frames.get(0));applyHitRange(frames.get(0));applyEntityFrames();applyRidingRelationships(frames.get(0));applyBlockActions(0);applyChatMessages(0);}} private boolean shouldSelfStop(){return root||!modifiers.waitForParentEnd();}
    private void applyFrame(PlayerStateFrame f){Location l=transform(new Location(targetWorld,f.x(),f.y(),f.z(),f.yaw(),f.pitch()));if(entityActor!=null)entityActor.apply(f,l);else{fakePlayer.apply(f);fakePlayer.getBukkitEntity().teleport(l);}} private void applyHitRange(PlayerStateFrame f){HitRangePlayback.apply(playbackPlayerEntity(),f.swingMainHand(),f.swingOffHand());}
    private void applyEntityFrames(){if(!playEntities.enabled())return;for(Map.Entry<UUID,List<EntityStateFrame>> e:entityFrames.entrySet()){List<EntityStateFrame> t=e.getValue();EntityStateFrame f=frameAtTick(t,tick);EntityPlaybackActor a=entityActors.get(e.getKey());if(f==null){if(a!=null){eject(a.entity());a.remove();entityActors.remove(e.getKey());}continue;}if(a==null){EntityType type=EntityType.fromName(f.entityType());if(type==null||type==EntityType.PLAYER||!playEntities.matches(type))continue;Location l=transform(new Location(targetWorld,f.x(),f.y(),f.z(),f.yaw(),f.pitch()));try{a=new EntityPlaybackActor(targetWorld.spawnEntity(l,type),modifiers.sceneScale(),invulnerablePlayback);entityActors.put(e.getKey(),a);}catch(IllegalArgumentException ignored){continue;}}a.apply(f,transform(new Location(targetWorld,f.x(),f.y(),f.z(),f.yaw(),f.pitch())));}}
    private void applyRidingRelationships(PlayerStateFrame pf){Entity p=playbackPlayerEntity();if(p==null)return;UUID id=pf.vehicleId();if(id==null)eject(p);else{EntityPlaybackActor v=entityActors.get(id);if(v!=null&&v.entity().isValid())v.entity().addPassenger(p);else eject(p);}if(!playEntities.enabled())return;for(Map.Entry<UUID,List<EntityStateFrame>> e:entityFrames.entrySet()){EntityPlaybackActor a=entityActors.get(e.getKey());if(a==null||!a.entity().isValid())continue;EntityStateFrame f=frameAtTick(e.getValue(),tick);if(f==null)continue;UUID vid=f.vehicleId();if(vid==null)eject(a.entity());else{EntityPlaybackActor v=entityActors.get(vid);if(v!=null&&v.entity().isValid()&&v.entity()!=a.entity())v.entity().addPassenger(a.entity());else eject(a.entity());}}}
    private void initializeBlocks(){if(!blockInitialization)return;for(BlockActionFrame a:blockActions){BlockData before=createTransformedBlockData(a.beforeState());for(Location l:transformedBlockLocations(a)){if(before==null)continue;try{l.getBlock().setBlockData(before.clone(),false);}catch(IllegalArgumentException ignored){}}}}
    private void applyBlockActions(long target){if(!blockActionsPlayback)return;boolean dropFromBlocks=JavaPlugin.getProvidingPlugin(PlaybackSession.class).getConfig().getBoolean("settings.drop_from_blocks",false);for(BlockActionFrame a:blockActions){if(a.tick()!=target||a.action()==BlockActionFrame.Action.INTERACT)continue;for(Location l:transformedBlockLocations(a)){try{if(a.action()==BlockActionFrame.Action.BREAK){if(dropFromBlocks)for(var drop:l.getBlock().getDrops())l.getWorld().dropItemNaturally(l,drop);l.getBlock().setType(org.bukkit.Material.AIR,false);}else{BlockData after=createTransformedBlockData(a.afterState());if(after!=null)l.getBlock().setBlockData(after.clone(),false);}}catch(IllegalArgumentException ignored){}}}}
    private BlockData createTransformedBlockData(String state){try{return transformer.transformBlockState(Bukkit.createBlockData(state));}catch(IllegalArgumentException ignored){return null;}} private List<Location> transformedBlockLocations(BlockActionFrame a){List<Vector> positions=transformer.transformBlockPositions(new Vector(a.x(),a.y(),a.z()),blockAllowScaled);if(positions.isEmpty())return List.of();return positions.stream().map(p->new Location(targetWorld,Math.floor(p.getX()),Math.floor(p.getY()),Math.floor(p.getZ()))).toList();}
    private void applyChatMessages(long target){if(!chatPlayback)return;for(ChatMessageFrame chat:chatMessages){if(chat.tick()!=target)continue;try{Component message=GsonComponentSerializer.gson().deserialize(chat.messageJson());Bukkit.broadcast(Component.text("<").append(Component.text(recording.getSourcePlayerName())).append(Component.text("> ")).append(message));}catch(Exception ignored){}}}
    private Entity playbackPlayerEntity(){if(entityActor!=null)return entityActor.entity();return fakePlayer==null?null:fakePlayer.getBukkitEntity();} private void ejectPlayer(){Entity p=playbackPlayerEntity();if(p!=null)eject(p);} private static void eject(Entity p){Entity v=p.getVehicle();if(v!=null)v.removePassenger(p);} private static long lastTick(List<EntityStateFrame> t){return t.isEmpty()?Long.MIN_VALUE:t.get(t.size()-1).tick();} private static EntityStateFrame frameAtTick(List<EntityStateFrame> t,long target){int lo=0,hi=t.size()-1;while(lo<=hi){int m=(lo+hi)>>>1;long v=t.get(m).tick();if(v<target)lo=m+1;else if(v>target)hi=m-1;else return t.get(m);}return null;} private void removeRecordedEntities(){for(EntityPlaybackActor a:entityActors.values()){eject(a.entity());a.remove();}entityActors.clear();} public Location resolveLocation(Player fallback){PlayerStateFrame f=currentFrame();if(f==null)return fallback.getLocation().clone();return transform(new Location(targetWorld,f.x(),f.y(),f.z(),f.yaw(),f.pitch()));} private Location transform(Location l){return transformer.transform(l);}
    private GameProfile resolveProfile(Player viewer){PlayerSkin s=modifiers.playerSkin();if(s.isSkinList()){PlayerSkin resolved=SkinListRepository.loadRandom(targetWorld.getWorldFolder().toPath(),s.path(),new Random());if(resolved!=null)s=resolved;}if(s.source()==PlayerSkin.Source.FROM_PLAYER){Player p=findPlayerByName(s.path());if(p!=null)return ((CraftPlayer)p).getProfile();}if(s.source()==PlayerSkin.Source.FROM_MINESKIN){Property p=MineSkinSkins.getProperty(s.path());if(p!=null){GameProfile g=new GameProfile(UUID.randomUUID(),modifiers.playerName()==null?"MoCap":modifiers.playerName());g.properties().put("textures",p);return g;}}if(startAsRecorded&&recording.getAssignedProfile()!=null&&recording.getAssignedProfile().name()!=null&&!"no".equals(assignProfileMode)){RecordingSession.AssignedProfile ap=recording.getAssignedProfile();if("full".equals(assignProfileMode)&&ap.id()!=null&&ap.skinValue()!=null&&ap.skinSignature()!=null){GameProfile g=new GameProfile(ap.id(),ap.name());g.properties().put("textures",new Property("textures",ap.skinValue(),ap.skinSignature()));return g;}if("only_name".equals(assignProfileMode))return new GameProfile(UUID.randomUUID(),ap.name());}if(modifiers.playerName()!=null){if(s.source()==PlayerSkin.Source.DEFAULT)return resolveNamedProfileWithoutSkin(viewer,modifiers.playerName());return resolveNamedProfile(viewer,modifiers.playerName());}if(s.source()==PlayerSkin.Source.DEFAULT)return resolveViewerProfileWithoutSkin(viewer);return ((CraftPlayer)viewer).getProfile();}
    private GameProfile resolveNamedProfileWithoutSkin(Player viewer,String name){if("disable_loading_profiles".equalsIgnoreCase(playerNameHandling))return new GameProfile(UUID.randomUUID(),name);boolean useAuthlibServices=JavaPlugin.getProvidingPlugin(PlaybackSession.class).getConfig().getBoolean("settings.use_authlib_services",false);try{net.minecraft.server.MinecraftServer server=((CraftServer)Bukkit.getServer()).getServer();ProfileUtils.Profile profile=ProfileUtils.getProfile(server,playerNameHandling,name,false,useAuthlibServices);return new GameProfile(UUID.randomUUID(),profile.name());}catch(Exception ignored){return new GameProfile(UUID.randomUUID(),name);}}
    private GameProfile resolveViewerProfileWithoutSkin(Player viewer){return new GameProfile(UUID.randomUUID(),viewer.getName());}
    private GameProfile resolveNamedProfile(Player viewer,String name){if("disable_loading_profiles".equalsIgnoreCase(playerNameHandling))return new GameProfile(UUID.randomUUID(),name);boolean useAuthlibServices=JavaPlugin.getProvidingPlugin(PlaybackSession.class).getConfig().getBoolean("settings.use_authlib_services",false);try{net.minecraft.server.MinecraftServer server=((CraftServer)Bukkit.getServer()).getServer();ProfileUtils.Profile profile=ProfileUtils.getProfile(server,playerNameHandling,name,true,useAuthlibServices);if(profile.skin()!=null)return ProfileUtils.toGameProfile(profile);return new GameProfile(UUID.randomUUID(),profile.name());}catch(Exception ignored){Player p=findPlayerByName(name);if(p!=null)return ((CraftPlayer)p).getProfile();return new GameProfile(UUID.randomUUID(),name);}}
    private Player findPlayerByName(String name){if(name==null)return null;Player exact=Bukkit.getPlayerExact(name);if(exact!=null)return exact;if(!"ignore_casing".equalsIgnoreCase(playerNameHandling)&&!"ignore_and_replace_casing".equalsIgnoreCase(playerNameHandling))return null;for(Player p:Bukkit.getOnlinePlayers())if(p.getName().equalsIgnoreCase(name))return p;return null;}
    private Vector calculateRecordingCenter(){if(frames.isEmpty())return new Vector(0,0,0);PlayerStateFrame s=frames.get(0);Vector p=new Vector(s.x(),s.y(),s.z());PlaybackModifiers.TransformationConfig c=modifiers.transformationConfig();Vector center=switch(c.recordingCenter()){case ACTUAL->p.clone();case BLOCK_CENTER->blockCenter(p);case BLOCK_CORNER->blockCorner(p);case AUTO->autoCenter(p);};return center.add(new Vector(c.centerOffsetX(),c.centerOffsetY(),c.centerOffsetZ()));} private Vector autoCenter(Vector p){double s=modifiers.sceneScale();if(s==1.0||s!=Math.rint(s)){Vector c=blockCenter(p),q=blockCorner(p);return p.distanceSquared(c)>p.distanceSquared(q)?q:c;}return blockCenter(p);} private Vector blockCenter(Vector p){return new Vector(Math.floor(p.getX())+0.5,Math.floor(p.getY())+0.5,Math.floor(p.getZ())+0.5);} private Vector blockCorner(Vector p){return new Vector(Math.floor(p.getX()),Math.floor(p.getY()),Math.floor(p.getZ()));} private long secondsToTicks(double seconds){return Math.max(0L,Math.round(seconds*20.0));}
}